import { getOpportunityLaneById } from "./opportunityPlaybook.js";

export const accountOpportunityPlaybook = {
  businessProfile: {
    coreBusiness: [
      "海外官方 AI 账号与订阅",
      "海外 API 或合规中转",
      "教程与 FAQ",
      "代配置和迁移服务",
      "交易风控与售后边界",
    ],
    targetUsers: [
      "经营海外 AI 工具的中文卖家",
      "准备购买海外 AI 账号、订阅或开发工具的普通用户",
      "需要降低支付、登录、额度和售后不确定性的买卖双方",
    ],
    tone: "直接、克制、可核验；像经营晨会，不像促销软文",
    editorialRule:
      "只处理海外 AI 产品；先看真实来源，再决定今天是试挂低风险交付、修改标题或教程、更新 FAQ、收紧售后边界还是不动作。",
  },

  strategyKernel: {
    formula:
      "真实信号 + 明确供给形态 + 一个最小动作 + 可观察结果 + 售后与合规边界。",
    operatingRules: [
      "DeepSeek、豆包、Kimi、MiniMax、通义、智谱、文心、腾讯混元、讯飞等国内 AI 产品不进入本栏目",
      "国内产品与海外产品的比较稿，只有海外产品自身出现可核验新变化时才可采用",
      "模型能力新闻不能直接证明账号价格、额度或政策变化，但可以触发教程、选型、迁移、组合体验或标题实验",
      "社交信息可以发现真实使用场景；价格、套餐、额度、支付、地区、登录、政策和服务状态仍必须回到官方页面",
      "没有官方硬信号时也可做低风险的教程、FAQ、选型说明或标题测试，但不得虚构商品状态和平台变化",
      "普通买家也应能从文章中判断是否值得买、购买前应核对什么",
      "禁止共享滥用、凭据转卖、盗号、黑卡、接码、绕过验证和规避风控建议",
    ],
    supplyForms: [
      "官方订阅",
      "官方账号",
      "API或中转",
      "第三方入口",
      "激活工具",
      "教程资料",
      "代配置服务",
    ],
  },

  productLanes: [
    {
      id: "account",
      name: "海外官方账号与订阅",
      description: "只讨论海外产品中来源、功能范围和平台条款能够核验的账号或订阅变化。",
      sellFormats: ["官方订阅入口", "正规账号交付", "购买前核验说明"],
      scoringProfile: {
        catalogFit: 30,
        standardDelivery: 14,
        lowPriceLeadGen: 8,
        upsellFit: 8,
      },
    },
    {
      id: "bundle",
      name: "教程与决策资料",
      description: "把真实变化写成选型 FAQ、上手说明和售后边界，不强制搭售账号。",
      sellFormats: ["选型 FAQ", "上手教程", "风险核对清单"],
      scoringProfile: {
        catalogFit: 24,
        standardDelivery: 18,
        lowPriceLeadGen: 6,
        upsellFit: 10,
      },
    },
    {
      id: "service",
      name: "合规轻服务",
      description: "围绕海外 AI 工具提供固定范围的代配置、迁移说明和问题排查，不代绕过平台限制。",
      sellFormats: ["代配置", "迁移说明", "购买前环境核对"],
      scoringProfile: {
        catalogFit: 22,
        standardDelivery: 18,
        lowPriceLeadGen: 4,
        upsellFit: 10,
      },
    },
  ],

  topicRules: [
    {
      id: "gpt-account",
      label: "OpenAI 账号与订阅信号",
      match: ["openai", "chatgpt", "gpt", "plus", "pro", "subscription"],
      preferredLane: "account",
      secondaryLane: "bundle",
      supplyForm: "official-subscription",
      buyerPain: "plan-selection",
      actionType: "faq-or-offer-review",
      defaultAdvice: "官方变化优先写套餐与边界；普通产品更新则写成场景教程、选型说明或低风险标题实验，不把热度当成交证据。",
      productAngle: "套餐核对 / 场景教程 / 低风险体验说明",
      buyerHint: "正在比较套餐、额度和适用场景的买家",
      deliveryHint: "套餐核对、场景教程、选型 FAQ 和不能承诺项",
      channelHint: "商品 FAQ、售前咨询和售后说明",
      titleHint: "先写买家要核对的变化，再写产品名",
      avoidLeadHint: "不要写未经证实的封号、降价、销量或稳定性",
    },
    {
      id: "claude-account",
      label: "Claude 账号与订阅信号",
      match: ["claude", "anthropic", "sonnet", "opus", "max plan", "pro plan"],
      preferredLane: "account",
      secondaryLane: "bundle",
      supplyForm: "official-subscription",
      buyerPain: "plan-selection",
      actionType: "faq-or-offer-review",
      defaultAdvice: "官方变化写套餐与条款；功能和工作流更新可写成上手教程、迁移说明或标题测试。",
      productAngle: "Claude 套餐核对 / 编程场景教程 / 迁移说明",
      buyerHint: "需要确认 Claude 套餐和使用边界的买家",
      deliveryHint: "套餐 FAQ、编程场景教程、迁移清单和售后边界",
      channelHint: "商品 FAQ、售前咨询和教程",
      titleHint: "先写变化和适用人群，再写 Claude",
      avoidLeadHint: "不要承诺稳定、额度或永不封号",
    },
    {
      id: "gemini-account",
      label: "Gemini 账号与订阅信号",
      match: ["gemini", "google ai", "google one", "ai pro", "ai ultra"],
      preferredLane: "account",
      secondaryLane: "bundle",
      supplyForm: "official-subscription",
      buyerPain: "region-or-plan-selection",
      actionType: "faq-or-offer-review",
      defaultAdvice: "官方变化写套餐与地区；产品能力更新可写成场景教程、选型说明或低风险体验组合。",
      productAngle: "Gemini 套餐核对 / 场景教程 / 体验说明",
      buyerHint: "担心地区、支付或套餐差异的买家",
      deliveryHint: "官方适用范围、场景教程、购买前检查和使用边界",
      channelHint: "商品 FAQ、售前咨询和教程",
      titleHint: "先写购买前要确认的限制，再写 Gemini",
      avoidLeadHint: "不要把普通功能发布写成账号上新理由",
    },
    {
      id: "api-access",
      label: "API 与开发入口信号",
      match: ["api pricing", "api key", "rate limit", "token price", "api 价格", "速率限制", "开发者套餐"],
      preferredLane: "service",
      secondaryLane: "bundle",
      supplyForm: "api-or-proxy",
      buyerPain: "api-cost-or-access",
      actionType: "configuration-or-faq-update",
      defaultAdvice: "区分官方 API、合规中转和来源不明密钥；不提供密钥买卖或绕限教程。",
      productAngle: "API 成本、限制与接入边界核对",
      buyerHint: "需要控制调用成本或确认接入限制的开发者",
      deliveryHint: "官方价格核对、固定范围代配置和失败排查",
      channelHint: "开发工具商品页、FAQ 和技术支持",
      titleHint: "先写成本或限制变化，再写 API 名称",
      avoidLeadHint: "不要售卖来源不明 API key，不要承诺绕过限额",
    },
    {
      id: "account-risk",
      label: "登录、封禁与服务状态信号",
      match: ["封号", "封禁", "冻结", "suspend", "suspension", "登录限制", "login", "outage", "服务状态"],
      preferredLane: "bundle",
      secondaryLane: "service",
      supplyForm: "risk-guidance",
      buyerPain: "account-interruption",
      actionType: "aftersales-boundary-update",
      defaultAdvice: "只有官方状态页或条款能支持确定性结论；优先更新售后边界，不制造恐慌。",
      productAngle: "登录或服务异常的核验与售后说明",
      buyerHint: "遇到登录或服务中断、需要判断原因的用户",
      deliveryHint: "官方状态核对、排查清单和明确的不包含项",
      channelHint: "售后公告、FAQ 和私聊排查",
      titleHint: "先写可确认的状态和处理边界",
      avoidLeadHint: "不要把单个用户反馈写成全球封号",
    },
    {
      id: "payment-region",
      label: "支付与地区限制信号",
      match: ["支付失败", "绑卡", "payment", "billing", "card", "地区限制", "region", "country"],
      preferredLane: "bundle",
      secondaryLane: "service",
      supplyForm: "managed-configuration",
      buyerPain: "payment-or-region",
      actionType: "buyer-checklist-update",
      defaultAdvice: "写购买前核对和官方支持范围，不提供绕过支付或地区限制的方法。",
      productAngle: "支付与地区适用性检查",
      buyerHint: "购买前需要确认支付方式和地区支持的用户",
      deliveryHint: "官方支持范围、购买前清单和退款边界",
      channelHint: "商品 FAQ、售前咨询和售后说明",
      titleHint: "先写购买前要核对什么",
      avoidLeadHint: "不要宣传代过验证、接码或规避地区限制",
    },
    {
      id: "pricing-quota",
      label: "价格、额度与套餐变化信号",
      match: ["涨价", "降价", "pricing", "price", "免费额度", "quota", "配额", "usage limit", "套餐"],
      preferredLane: "bundle",
      secondaryLane: "account",
      supplyForm: "official-subscription",
      buyerPain: "budget-or-quota-change",
      actionType: "price-and-faq-review",
      defaultAdvice: "官方价格和额度变化可以触发商品说明复核，但不能据此编造建议售价或买家热度。",
      productAngle: "官方价格、额度和现有商品说明复核",
      buyerHint: "需要判断套餐是否仍适合自己用量的买家",
      deliveryHint: "官方价格证据、用量问题清单和商品说明修订",
      channelHint: "商品详情、FAQ 和售前咨询",
      titleHint: "先写变化及其影响，再写产品名",
      avoidLeadHint: "不要编造闲鱼价格、利润率或销量",
    },
  ],

  outputRules: {
    maxPromptCandidates: 4,
    maxPublishedOpportunities: 2,
    maxDigestCandidates: 4,
    maxEvidenceItemsPerCandidate: 3,
    minimumCandidateScore: 52,
    requireAccountLikeOpportunityInTodayCanSell: false,
    requireDistinctCreativityModes: false,
    dailyCreativityModeCount: 3,
    requireSections: ["30 秒结论", "今日硬信号", "今日可执行", "买家避坑", "今天别碰", "今日三步"],
    requiredOpportunityFields: [
      "证据与可信度",
      "供给形态",
      "适合买家与真实需求",
      "是否今天能挂闲鱼",
      "今天最小动作",
      "售后与合规",
      "不能承诺与停止",
    ],
    requiredDecisionValues: {
      confidence: ["高", "中", "低"],
      xianyuToday: ["是", "否", "观察"],
      afterSalesRisk: ["低", "中", "高"],
    },
    creativityModes: [
      {
        id: "official_signal",
        label: "官方信号复核型",
        summary: "把官方变化翻译成商品说明或 FAQ 调整。",
        monetizationHint: "减少错误承诺和售后返工。",
        starterMove: "今天先核对一条官方页面并改一个字段。",
        avoid: "不要把功能新闻硬改成商品。",
      },
      {
        id: "buyer_guard",
        label: "买家避坑型",
        summary: "帮助普通买家在付款前核对来源、套餐和适用范围。",
        monetizationHint: "用透明边界建立长期信任。",
        starterMove: "今天先补一条购买前核对项。",
        avoid: "不要用恐慌促进成交。",
      },
      {
        id: "service_boundary",
        label: "售后边界型",
        summary: "根据官方状态或条款收紧不能承诺的范围。",
        monetizationHint: "降低不必要的售后成本。",
        starterMove: "今天先删除一个无法证明的稳定性承诺。",
        avoid: "不要写成免责甩锅。",
      },
    ],
    bannedClaims: [
      "不得编造销量、利润率、价格、库存、封号规模或平台政策。",
      "不得提供共享滥用、凭据转卖、盗号、黑卡、接码、绕过验证或规避风控建议。",
      "不得承诺长期稳定、永不封号、官方授权或无条件可用。",
      "不得把普通模型新闻硬写成账号商品机会。",
    ],
    bannedPublicPhrases: [
      "便宜 token",
      "风险自负",
      "多用户商业化",
      "永不封号",
      "无限续杯",
      "代过验证",
    ],
  },
};

export function serializeAccountOpportunityPlaybook(
  playbook = accountOpportunityPlaybook
) {
  const business = playbook.businessProfile;
  const strategy = playbook.strategyKernel || {};
  const lanes = playbook.productLanes
    .map((lane) => [
      `- ${lane.name}: ${lane.description}`,
      `  - 可用交付: ${lane.sellFormats.join("、")}`,
    ].join("\n"))
    .join("\n");
  const rules = playbook.topicRules
    .map((rule) => {
      const preferredLane = getOpportunityLaneById(rule.preferredLane, playbook);
      const secondaryLane = getOpportunityLaneById(rule.secondaryLane, playbook);
      return [
        `- ${rule.label}`,
        `  - 命中词: ${rule.match.join("、")}`,
        `  - 优先处理: ${preferredLane?.name || rule.preferredLane}`,
        `  - 备选处理: ${secondaryLane?.name || rule.secondaryLane}`,
        `  - 供给形态: ${rule.supplyForm}`,
        `  - 买家痛点: ${rule.buyerPain}`,
        `  - 行动类型: ${rule.actionType}`,
        `  - 编辑提醒: ${rule.defaultAdvice}`,
      ].join("\n");
    })
    .join("\n");

  return [
    "### 当前业务",
    `- 核心范围: ${business.coreBusiness.join("、")}`,
    `- 服务对象: ${business.targetUsers.join("、")}`,
    `- 语气: ${business.tone}`,
    `- 编辑原则: ${business.editorialRule}`,
    "",
    "### 经营与风控内核",
    "- 市场范围: 只处理海外 AI 账号、订阅、API 和开发工具；国内 AI 产品不进入候选、观察或行动",
    `- 总公式: ${strategy.formula}`,
    `- 操作规则: ${(strategy.operatingRules || []).join("；")}`,
    `- 供给形态必须选自: ${(strategy.supplyForms || []).join("、")}`,
    "",
    "### 可执行方向",
    lanes,
    "",
    "### 信号映射",
    rules,
    "",
    "### 输出硬规则",
    `- 每日最多 ${playbook.outputRules.maxPublishedOpportunities} 个行动，不凑数量。`,
    `- 必须包含: ${playbook.outputRules.requireSections.join("、")}`,
    `- 每个行动必须包含: ${playbook.outputRules.requiredOpportunityFields.join("、")}`,
    `- 可信度只能使用: ${playbook.outputRules.requiredDecisionValues.confidence.join("、")}`,
    `- 是否今天能挂闲鱼只能使用: ${playbook.outputRules.requiredDecisionValues.xianyuToday.join("、")}`,
    `- 售后风险只能使用: ${playbook.outputRules.requiredDecisionValues.afterSalesRisk.join("、")}`,
    "",
    "### 禁止乱写",
    ...playbook.outputRules.bannedClaims.map((item) => `- ${item}`),
    ...playbook.outputRules.bannedPublicPhrases.map((item) => `- 禁止公开使用措辞: ${item}`),
  ].join("\n");
}
